spring:
  application:
    name: fitness-app
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        globally_quoted_identifiers: true